### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by willbchang** [willbchang/chrome-read-later#118]
- [ ] Improve the document for developers
- [ ] Replace https://github.com/fb55/entities with https://github.com/mathiasbynens/he
- [ ] Make https://github.com/antongunov/favicongrabber.com inside the project, use chrome itself to grab favicon.
- [ ] Try to replace node with deno
- [ ] A better status bar at the bottom: reading list count, document link...
- [ ] Add shortcuts `Command + ↑` `Command + ↓` to behave like macos
- [ ] Record video/audio progress
- [ ] Record PDF progress
- [ ] A more dynamic VIM normal mode
- [ ] Port this to Safari
