### ISSUE TITLE
Iteration Plan November 2019

### ISSUE THREAD

**Issue by willbchang** [willbchang/chrome-read-later#46]
## Learning
- [ ] JS Test Framework: [Mocha](https://mochajs.org)
- [ ] [Refactoring](https://learning.oreilly.com/library/view/refactoring-improving-the/9780134757681): Chapter 2 ~ 4

## Dependencies
- [x] Apply ESLint

## Refactoring
- [x] `set({ [page.url]: { ...page, ...position } })`

## Bugs
- [x] Cannot avoid non-url link item in reading list #37
- [x] Cannot avoid adding about:blank #36 
- [x] Cannot remove clicked item while loading clicked url in tab #34 

## Features
- [x] Close tab after loading or save basic info #38 
- [x] Improve reading list readability by adding letter and word spacing #7 
- [x] Window animate scroll position #39 
- [ ] Video/Audio currentTime save and set #40 
- [x] Mouse Hover Show Link #41 
- [ ] Dynamic scroll position in different window size #42 

## Contribution
- [ ] Comments
- [ ] Write review rubric
- [ ] Set issue template #15 
- [ ] Write contribution guide

**Comment by willbchang** [comment]
Please Check: https://www.reddit.com/r/learnjavascript/comments/e6sf1d/dynamically_set_scroll_position_according_to/
